# Si Railway inyecta la variable la usa; si no, va a tu PC
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/techlabdb}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:manchislindo}

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto local por defecto
server.port=${PORT:8080}
