# Si Railway inyecta la variable la usa; si no, va a tu PC
# Cambiamos por las variables nativas de Railway: MYSQLHOST, MYSQLPORT y MYSQLDATABASE
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:techlabdb}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:manchislindo}

# Configuracion de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto local por defecto
server.port=${PORT:8080}

# Permite que la cookie de sesión viaje de manera segura entre Netlify y Railway
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=none
